name: "eslint"
on:
  push:
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: NPM Install
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run eslint
        run: npm run eslint
